import { createRng } from './rng';
import type { Fighter } from './fighter';

export const CAREER_TUNING = { ranks: { Rookie: 0, Bronze: 5, Silver: 15, Gold: 30, Platinum: 50, Elite: 80, Champion: 120 } as const, matchTimeLimitTicks: 7200, tickRate: 60, offers: { openFee: 0, openPurse: 60, rookieFee: 20, rookiePurse: 100, veteranFee: 40, veteranPurse: 250, lossRank: 1, rookieWin: 1, veteranWin: 2 } } as const;
export type Outcome = 'win'|'loss'|'draw'|'forfeit';
export type Tier = 'rookie'|'veteran';
export interface Offer { id:string; tier:Tier; opponent:string; fee:number; purse:number; rankPointsOnWin:number; matchSeed:number; exhibition?:boolean; dangerous?:boolean; }
export interface PendingMatch extends Offer { acceptedAt:number; }
export interface HistoryEntry { opponent:string; tier:Tier; outcome:Outcome; fee:number; payout:number; netCurrency:number; rankPointsDelta:number; durationSeconds:number; promotedTo?:string; }
export interface Career { rankPoints:number; wins:number; losses:number; draws:number; history:HistoryEntry[]; offerSeed:number; pendingMatch:PendingMatch|null; }
export interface CareerState { fighter:Fighter; career:Career; }
export const defaultCareer = (seed = Date.now()):Career => ({rankPoints:0,wins:0,losses:0,draws:0,history:[],offerSeed:seed>>>0,pendingMatch:null});
export function createOffers(seed:number, _fighter:Fighter, _career:Career):Offer[] { const rng=createRng(seed); const names=['Mara Venn','Kestrel-9','Orrin Vale','Sable Rook','Toma Ash']; const pick=()=>names[Math.floor(rng()*names.length)]; return [{id:'open-ring',tier:'rookie',opponent:pick(),fee:0,purse:CAREER_TUNING.offers.openPurse,rankPointsOnWin:0,matchSeed:(rng()*0xffffffff)>>>0,exhibition:true},{id:'rookie-bout',tier:'rookie',opponent:pick(),fee:CAREER_TUNING.offers.rookieFee,purse:CAREER_TUNING.offers.rookiePurse,rankPointsOnWin:1,matchSeed:(rng()*0xffffffff)>>>0},{id:'veteran-bout',tier:'veteran',opponent:pick(),fee:CAREER_TUNING.offers.veteranFee,purse:CAREER_TUNING.offers.veteranPurse,rankPointsOnWin:2,matchSeed:(rng()*0xffffffff)>>>0,dangerous:true}]; }
export function startMatch(state:CareerState, offer:Offer):CareerState { if(state.fighter.progression.currency<offer.fee) throw new Error('Insufficient credits'); return {fighter:{...state.fighter,progression:{...state.fighter.progression,currency:state.fighter.progression.currency-offer.fee}},career:{...state.career,pendingMatch:{...offer,acceptedAt:0}}}; }
function rankAt(points:number):keyof typeof CAREER_TUNING.ranks { return (Object.keys(CAREER_TUNING.ranks).reverse().find(k=>points>=CAREER_TUNING.ranks[k as keyof typeof CAREER_TUNING.ranks])||'Rookie') as keyof typeof CAREER_TUNING.ranks; }
export function settleMatch(state:CareerState,outcome:Outcome,durationTicks:number):{state:CareerState;summary:{outcome:Outcome;breakdown:string[];promotedTo?:string;[key:string]:unknown}} { const p=state.career.pendingMatch; if(!p) throw new Error('No pending match'); const oldRank=state.fighter.progression.rank; let payout=0, delta=0; if(outcome==='win'){const share=.10+createRng(p.matchSeed)()*.10;payout=p.fee+p.fee+Math.round(p.purse*share);delta=p.rankPointsOnWin;} else if(outcome==='draw'){payout=p.fee;} else if(!p.exhibition) delta=-Math.min(1,state.career.rankPoints); const currency=payout; const points=Math.max(0,state.career.rankPoints+delta); const candidateRank=rankAt(points); const rankOrder=Object.keys(CAREER_TUNING.ranks); const currentIndex=rankOrder.indexOf(oldRank); const candidateIndex=rankOrder.indexOf(candidateRank); const finalRank=rankOrder[Math.max(currentIndex,candidateIndex)] as keyof typeof CAREER_TUNING.ranks; const promoted=finalRank!==oldRank&&rankOrder.indexOf(finalRank)>currentIndex?finalRank:undefined; const history=[...state.career.history,{opponent:p.opponent,tier:p.tier,outcome,fee:p.fee,payout,netCurrency:payout-p.fee,rankPointsDelta:delta,durationSeconds:durationTicks/CAREER_TUNING.tickRate,...(promoted?{promotedTo:promoted}: {})}].slice(-50); const fighter={...state.fighter,progression:{...state.fighter.progression,currency:state.fighter.progression.currency+currency,rank:finalRank}}; return {state:{fighter,career:{...state.career,rankPoints:points,wins:state.career.wins+(outcome==='win'?1:0),losses:state.career.losses+(['loss','forfeit'].includes(outcome)?1:0),draws:state.career.draws+(outcome==='draw'?1:0),history,offerSeed:(state.career.offerSeed+1)>>>0,pendingMatch:null}},summary:{outcome,breakdown:[`Fee returned: ${outcome==='draw'?p.fee:outcome==='win'?p.fee:0}`,`Opponent fee: ${outcome==='win'?p.fee:0}`,`Purse share: ${outcome==='win'?Math.round(payout-2*p.fee):0}`,`Net change: ${payout-p.fee}`],...(promoted?{promotedTo:promoted}: {})}}; }
export function resolvePendingOnLoad(state:CareerState){return state.career.pendingMatch?settleMatch(state,'forfeit',0):{state,summary:null};}
export function resolveFightResult(playerHealth:number,opponentHealth:number,ticks:number,limit=CAREER_TUNING.matchTimeLimitTicks):Outcome|null { if(playerHealth<=0&&opponentHealth<=0)return'draw'; if(opponentHealth<=0)return'win'; if(playerHealth<=0)return'loss'; if(ticks>=limit){const a=playerHealth, b=opponentHealth; return a===b?'draw':a>b?'win':'loss';} return null; }
